---
title: "ps_7"
author: "Kai Potter"
date: "11/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(fs)
library(lubridate)
library(formattable)
library(foreign)
library(kableExtra)
library(readr)
library(xml2)
library(stringr)
```

```{r loading_data, message=FALSE, cache = TRUE, warning=FALSE, error= FALSE, echo = FALSE}
#Loading the data into one dataframe using map_dfr. 
 download.file(url = "https://goo.gl/ZRCBda",
              destfile = "master.zip",
            quiet = TRUE, 
            mode = "wb") 
unzip("master.zip") 


filenames <- dir_ls("2018-live-poll-results-master/data/")

data <- map_dfr(filenames, read_csv, .id = "source")
 

```

```{r sorting_feminism, message=FALSE, warning=FALSE, error= FALSE, echo = FALSE}
#Here I am making a table to show the relationship between feminism and intended party vote. I had to sort out the party categories and use final weight, and spread and mutate response. 
feminism <- data %>%
mutate(response = case_when(
    response %in% c("Rep") ~ "Rep", 
    response %in% c("Dem") ~ "Dem",
    response %in% c("Und", "3", "4", "5") ~ "Und")) %>% 
  group_by(FEMINISM, response) %>% 
  tally(wt = final_weight) %>%
  filter(!is.na(response)) %>%
  spread(key = "response", value = "n") %>%
  mutate(total = Dem + Rep + Und) %>%
  mutate(Dem = 100*Dem / total, Rep = 100*Rep/total, Und = 100*Und/total, total = total*100/total) %>%
  select(-total) %>%
   filter(FEMINISM != "[DO NOT READ] Don't know/Refused") 
```


```{r sorting_gender, message=FALSE, warning=FALSE, error= FALSE, echo = FALSE}
#Here I am making a table to show the relationship between gender and intended party vote. I had to sort out the party categories and use final weight, and spread and mutate response. 
gender <- data %>%
mutate(response = case_when(
    response %in% c("Rep") ~ "Rep", 
    response %in% c("Dem") ~ "Dem",
    response %in% c("Und", "3", "4", "5") ~ "Und")) %>% 
  group_by(gender, response) %>% 
  tally(wt = final_weight) %>%
  filter(!is.na(response)) %>%
  spread(key = "response", value = "n") %>%
  mutate(total = Dem + Rep + Und) %>%
  mutate(Dem = 100*Dem / total, Rep = 100*Rep/total, Und = 100*Und/total, total = total*100/total) %>%
  select(-total) %>%
   filter(gender != "[DO NOT READ] Don't know/Refused") 
```


```{r sorting_turnout, message=FALSE, warning=FALSE, error= FALSE, echo = FALSE}
#Here I am making a table to show the relationship between turnout and intended party vote. I had to sort out the party categories and use final weight, and spread and mutate response. 
turnout <- data %>%
mutate(response = case_when(
    response %in% c("Rep") ~ "Rep", 
    response %in% c("Dem") ~ "Dem",
    response %in% c("Und", "3", "4", "5") ~ "Und")) %>% 
  group_by(turnout_class, response) %>% 
  tally(wt = final_weight) %>%
  filter(!is.na(response)) %>%
  spread(key = "response", value = "n") %>%
  mutate(total = Dem + Rep + Und) %>%
  mutate(Dem = 100*Dem / total, Rep = 100*Rep/total, Und = 100*Und/total, total = total*100/total) %>%
  select(-total) %>%
   filter(turnout_class != "[DO NOT READ] Don't know/Refused")


```

```{r preparing_bind, message=FALSE, warning=FALSE, error= FALSE, echo = FALSE}
#Here I am renaming the categories and mutating them to create a new variable column so it's easy to bind everything together. 


Feminism <- feminism %>% 
  rename(category = FEMINISM) %>%
  mutate(variable = "feminism")

Gender <- gender %>% 
  rename(category = gender) %>%
  mutate(variable = "gender")

Turnout <- turnout %>% 
  rename(category = turnout_class) %>%
  mutate(variable = "turnout")

#Here I bind rows to make it easier to manipulate data in app.R. 

joined <- Feminism %>%
  bind_rows(Gender) %>%
  bind_rows(Turnout) 
joined 






```


```{r writing_rds, message=FALSE, warning=FALSE, error= FALSE, echo = FALSE}
#Here I use write_rds to transfer the data over to app.R. 
write_rds(joined, "ps_7shiny/joined.rds")

```

